# Generated by Django 4.0.1 on 2022-01-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ntegumentary', 'Integumentary System'), ('skeletal', 'Skeletal System'), ('muscular', 'Muscular System'), ('lymphatic', 'Lymphatic System'), ('respiratory', 'Respiratory System'), ('digestive', 'Digestive System'), ('nervous', 'Nervous System'), ('endocrine', 'Endocrine System'), ('cardiovascular', 'Cardiovascular System'), ('urinary', 'Urinary System'), ('reproductive', 'Reproductive Systems')], default='integumentary', max_length=255),
        ),
    ]
