# Generated by Django 4.0.1 on 2022-01-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Integumentary System', 'Integumentary System'), ('Skeletal System', 'Skeletal System'), ('Muscular System', 'Muscular System'), ('Lymphatic System', 'Lymphatic System'), ('Respiratory System', 'Respiratory System'), ('Digestive System', 'Digestive System'), ('Nervous System', 'Nervous System'), ('Endocrine System', 'Endocrine System'), ('Cardiovascular System', 'Cardiovascular System'), ('Urinary System', 'Urinary System'), ('Reproductive System', 'Reproductive Systems')], default='integumentary', max_length=255),
        ),
    ]
